#Anything that is optional which you are not using, just delete that line. You can also delete any of the '#comments'

modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved" #mandatory https://choosealicense.com/

[[mods]] #mandatory
modId="fiery_stuff" #mandatory
version="1.0" #mandatory
displayName="Fiery Stuffs" #mandatory
credits="This Mod is made by Atharva and is Inspired by Twilight forest Fiery ingot and Fiery Items" #optional
authors="Atharva Mishra/MagiYunon" #optional
description='''
This is a Mod that adds in a Fiery items from twilight forest in a new way by adding fiery ores and fiery axes and shovel.
BUT ALL OF THE CREDITS GOES TO TWILIGHT FOREST MOD. 
''' #mandatory
